[project]
name = "backup-service"
version = "0.1.0"
description = "Tool for doing backups"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "pydantic>=2.10.4",
]

[dependency-groups]
dev = [
    "ruff>=0.8.5",
]
